### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by Maxine-Chui** [Maxine-Chui/Fullstack_Instaclone#1]
- [x] initial push to heroku
- [ ] prepare app for production

**Comment by Maxine-Chui** [comment]
https://fsp-instaclone.herokuapp.com/#/

**Comment by anastassia-b** [comment]
- [ ] Replace all image http: with https: to prevent console warning.

**Comment by Maxine-Chui** [comment]
new heroku link: https://fsp-offthegrid.herokuapp.com/#/
