### ISSUE TITLE
PA Review: Comments

### ISSUE THREAD

**Issue by Maxine-Chui** [Maxine-Chui/Fullstack_Instaclone#6]

**Comment by anastassia-b** [comment]
Great progress on this feature. The core comment functionality is working. To complete this MVP:
- [x] allow the user to submit a comment by hitting "enter"
- [x] correctly add the comment to the bottom of the list 
- [x] have no errors in deleting own comments

**Comment by anastassia-b** [comment]
Awesome, this MVP is complete.
